/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import ppl.koneksi;

/**
 *
 * @author JEE
 */
public class isiPenyakit extends javax.swing.JFrame {

    /**
     * Creates new form isidata
     */
    koneksi kon;
    public isiPenyakit() throws SQLException {
        initComponents();
        kon = new koneksi("ppl", "root", "");
        jenisPohon();
        kondisiBuah();
        kondisiPohon();
        kondisidaun();
    }

    public void jenisPohon() throws SQLException {
        String query = "SELECT * FROM penyakit group by jenisPohon ";
        ResultSet rs = kon.getResult(query);
        while (rs.next()) {
            jenisPohon_cb.addItem(rs.getString("jenisPohon"));
        }
    }
     public void kondisiBuah() throws SQLException {
        String query = "SELECT * FROM penyakit group by kondisiBuah ";
        ResultSet rs = kon.getResult(query);
        while (rs.next()) {
            kondisiBuah_cb.addItem(rs.getString("kondisiBuah"));
        }
    }
      public void kondisiPohon() throws SQLException {
        String query = "SELECT kondisiPohon FROM penyakit group by kondisiPohon ";
        ResultSet rs = kon.getResult(query);
        while (rs.next()) {
            kondisiPohon_cb.addItem(rs.getString("kondisiPohon"));

        }
    }
       public void kondisidaun() throws SQLException {
        String query = "SELECT * FROM penyakit group by kondisiDaun ";
        ResultSet rs = kon.getResult(query);
        while (rs.next()) {
            kondisiDaun_cb.addItem(rs.getString("kondisiDaun"));

        }
    }
    public JComboBox <String> getjenisPohon() {
        return jenisPohon_cb;

    }

    public JComboBox <String> getkondisiPohon() {
        return kondisiPohon_cb;

    }

    public JComboBox <String>  getkondisiBuah() {
        return kondisiBuah_cb;

    }

    public JComboBox <String>  getkondisiDaun() {
        return kondisiDaun_cb;

    }

    public JButton getAnalisa() {
        return analisa_btn;
    }
    
    public  JLabel getKembali(){
        return kembali_btn;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jenisPohon_cb = new javax.swing.JComboBox<>();
        kondisiPohon_cb = new javax.swing.JComboBox<>();
        kondisiBuah_cb = new javax.swing.JComboBox<>();
        kondisiDaun_cb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        analisa_btn = new javax.swing.JButton();
        kembali_btn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(891, 544));
        setPreferredSize(new java.awt.Dimension(891, 544));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(jenisPohon_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 460, 30));

        jPanel1.add(kondisiPohon_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 460, 30));

        jPanel1.add(kondisiBuah_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 460, 30));

        jPanel1.add(kondisiDaun_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 460, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Kondisi Buah Yang di Hasilkan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Kondisi Daun");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Kondisi Pohon");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Jenis Pohon");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        analisa_btn.setText("Ananlisa");
        analisa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analisa_btnActionPerformed(evt);
            }
        });
        jPanel1.add(analisa_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 150, 60));

        kembali_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back.png"))); // NOI18N
        jPanel1.add(kembali_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 830, 470));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LIHAT APA YANG TERJADI");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ab.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 891, 544));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analisa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analisa_btnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_analisa_btnActionPerformed
    private void kembali_btnMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:

    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isiPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isiPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isiPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isiPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new isiPenyakit().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(isiPenyakit.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analisa_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenisPohon_cb;
    private javax.swing.JLabel kembali_btn;
    private javax.swing.JComboBox<String> kondisiBuah_cb;
    private javax.swing.JComboBox<String> kondisiDaun_cb;
    private javax.swing.JComboBox<String> kondisiPohon_cb;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
